testsigmahq/testsigma

ui/src/app/components/webcomponents/action-step-form.component.ts

The element overlay is displayed as a blank screen when we edit the step and click on an empty element.

T0S-683 Empty Element Blank Overlay Issue

---

ui/src/app/components/cases/test-case-details.component.ts
ui/src/assets/i18n/en.json

Steps for reproduce
Create Test Case
Click on the delete icon in the Test case details page and observe 
Actual
The display text in the "Delete" Warning message popup is inappropriate in Test Case Details Page
Expected
The display text in the "Delete" Warning message popup to be displayed as same as it is displayed in cloud in the Test Case Details Page

Fix/tos 681 The display text in the "Delete" Warning message popup is inappropriate in Test Case Details Page

---

ui/src/assets/i18n/en.json

Actual
The warning message for Uploads is inappropriate i.e., it is displaying device names and stating as “Please detach the upload with the below test plans, and try deleting.“
Expected
The warning message to be displayed as “This Upload is used in the below Test Devices,
Please remove the mapping and try again.“

 TOS-730 The warning message for Uploads is inappropriate

---

server/src/main/java/com/testsigma/service/AgentExecutionService.java

**FILE**
`server/src/main/java/com/testsigma/service/AgentExecutionService.java  =>getExecutableSteps()`
Generally we are skipping the step who's parent step type is LOOP 
If that step have more sub steps we are not skipping those steps and in the end they are getting duplicated in final execution
what I did here is add the step ID's whose parent step type is LOOP to a List called skipIds
now If a step parent ID is present in skipIds we'll add skip that step and also add that stepId to skipIDs

TOS-759 "IF Conditionl" steps are getting duplicated for only the last iteration in a "FOR Loop"

---

ui/src/app/components/webcomponents/lab-environment-screen-short-info.component.ts
ui/src/app/shared/components/webcomponents/test-machine-info-column.component.ts

Chrome Browser is being displayed Instead of Edge / Firefox browsers in the Test plan view reports page
> Fixed the issue now the reports are showing correct browser information in reports
> Instead of retrieving information from test device, retrieving environment settings

Chrome Browser is being displayed Instead of Edge / Firefox browsers in the Test plan view reports page

---

ui/src/app/components/elements/list.component.html

When clicked on "Record" button for the Element Inspection , it displays "Loading" symbol continously but doesn't start the Recorder  this occurs only for the Record button that is displayed at the bottom of the Empty Element List Page

When clicked on "Record" button for the Element Inspection , it displays "Loading" symbol continously

---

agent/src/main/java/com/testsigma/agent/services/AgentService.java

Jira Link: https://testsigma.atlassian.net/browse/TOS-659
Windows 10 version builds:
First Release : 10.0.10240
Last Release : 10.0.19045
Windows 11 version builds:
First Release : 10.0.22000
Latest Release : 10.0.22621
The fix will segregate Windows 10 machines and Windows 11 machines using their build numbers.
Reference Links:
https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information
https://learn.microsoft.com/en-us/windows/release-health/release-information
[TOS-659]: https://testsigma.atlassian.net/browse/TOS-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TOS-659] fix (AgentService): OS version windows 11 version support added

---

agent/src/main/java/com/testsigma/agent/browsers/WindowsBrowsers.java

Jira Ticket: https://testsigma.atlassian.net/browse/TOS-890
Regex Expression  ".*(Microsoft Edge$)" will make sure that it will take values only which ends with Edge. Values with text after Edge will not be accepted.
In the registry entry,
"HKEY_CLASSES_ROOT\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\PackageRepository\\Packages"
There exists 3 Microsoft Edge entries. 
1. Microsoft.MicrosoftEdge.Stable_108.0.1462.54
2. Microsoft.MicrosoftEdge_44.22621.819.0
3. Microsoft.MicrosoftEdge.DevToolsClient_1000.22621.1.0
We require the Stable entry as it specifies the correct browser version. 
So the regex expression is modified into: ".*Microsoft.MicrosoftEdge.Stable_(.*)"
If stable is not present then, it will take the Edge_ value.

[TOS-890] fix : Microsoft Edge version in Windows

---

ui/src/app/components/webcomponents/result-status-label-info.component.ts

Jira Ticket: https://testsigma.atlassian.net/browse/TOS-958
Rerun status alignment looking not good
This occurs for all types of case scenarios, running, stopped, failed, etc
ml-25 was added to the tag irrespective of childResult. This fixes the problem. 
ml-25 was initially kept only for childResult but not its kept globally. So all classes will have the attribute ml-25

[TOS-958] fix: Rerun status alignment fixed

---

ui/src/app/components/webcomponents/action-element-suggestion.component.ts

Jira Ticket: https://testsigma.atlassian.net/browse/TOS-964
Github Issue: https://github.com/testsigmahq/testsigma/issues/266
**What is the current behavior?**
there's an issue with the external editor wherein if you try to edit an element, the elements inside the create / select element box which appears on the right side disappear
it happens only sometimes though.
**Actual**
Elements overlay page element list displaying empty
**Expected**
The elements list should show on the element overlay page
Fix:
Added support for symbols in element name so that query does not fail when calling for element list. symbol is converted to string and then passed.

[TOS-964] fix: Allowing elements to have symbols and display element list

---

server/src/main/resources/application.properties
ui/src/app/agents/enums/supported-device-type.ts
ui/src/app/shared/components/webcomponents/inspection-modal.component.ts
ui/src/app/shared/components/webcomponents/uploads-form.component.ts
ui/src/app/shared/models/upload.model.ts
ui/src/assets/i18n/en.json

Jira Ticket: https://testsigma.atlassian.net/browse/TOS-669
There is no any appropriate error message displayed in Mobile inspector when we use an Emulator ipa to record steps using Real Device
Steps for reproduce
Enable any storage
Upload an emulator app
Connect a Real Device
Create Test Case
Click on Record button within the Test Case
Select Real Device as the Device
select emulator ipa as the upload
Click on Record button
Wait until the app is uploaded and observe the Error message
Actual
There is no any appropriate error message displayed in Mobile inspector when we use an Emulator IPA to record steps using Real Device
Expected
There should be an appropriate error message displayed in Mobile inspector when we use an Emulator IPA to record steps using Real Device
Fix:
Have added a …

[TOS-669] fix : Checking ipa architecture and ios emulator/real-device

---

ui/src/app/components/webcomponents/test-step-list-item.component.ts

TOS-365
Fixes the wrong steps order, when we try to add a Teststep from Add step while hovering on a step
"Conditional IF" step is displayed in wrong order when we "add step" until the page is refreshed -->this occurs when cloned steps are present
[TOS-365]: https://testsigma.atlassian.net/browse/TOS-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TestStep):"Conditional IF" step is displayed in wrong order when when we "add step"

---

ui/src/app/components/cases/test-case-details.component.ts

Jira: https://testsigma.atlassian.net/browse/TOS-990 child issue
Parent issue: https://testsigma.atlassian.net/browse/TOS-789
Step groups are not getting deleted from its respective Test case when we try deleting it from Step Group Details page
Actual
It's not deleting until we delete it permanently
Expected
It should be deleted once we click on I understand, delete this Step group option
Fix
added the functionality to the delete button inside the step groups details page which was already present outside as a delete icon in the step groups list page.

[TOS-990] fix(test-case-details): removing step groups from test cases upon deletion

---

ui/src/app/components/cases/test-case-details.component.ts

Jira: https://testsigma.atlassian.net/browse/TOS-991
Parent issue: https://testsigma.atlassian.net/browse/TOS-789
Actual
Test cases list displaying under step group list when we delete step group permanently
Once we refresh its displaying correctly
Expected
It should not show the test case list under the step group list
Fix
redirecting to the step group list page after permanently deleting stepgroup using step group filter service.

[TOS-991] fix(test-case-details): test case list is displayed under step group

---

ui/src/app/services/test-step.service.ts

Jira Ticket: https://testsigma.atlassian.net/browse/TOS-963
Github Issue: https://github.com/testsigmahq/testsigma/issues/267
Issue: The test-data value present in the addon is changed the defaukt action text value when recorder is clicked.
Fix: The test-data value is now updated in the action text thus fixing the issue

[TOS-963] fix: Test-data in addons is modified in action text

---

automator/src/com/testsigma/automator/actions/web/generic/UploadFileAction.java

* Jira: https://testsigma.atlassian.net/browse/TOS-336
Not able to upload in Mobile web application using Nlp
* Actual
“Unable to perform specified action on current page - Appium error: An unknown server-side error occurred while processing the command. Original error: unknown error: path is not absolute: C:\Users\samisaac\AppData\Local\Temp\\1648903188621_Screenshot_(1).png (Session info: chrome=96.0.4664.104)” Message is displayed to user
* Expected
Should execute Upload Test step and img has to be uploaded
problem was that the temp path had two '\' which made it invalid.
added a condition to check whether the temp path ends with '\' and removed it if present.

[TOS-336] fix(UploadFileAction): removing '\' in temp dir path

---

ui/src/app/components/webcomponents/dry-run-form.component.html
ui/src/app/components/webcomponents/dry-run-form.component.ts

* Jira: https://testsigma.atlassian.net/browse/TOS-1054
Run now button should be disabled state until the all fields load
* Actual
Now run now button its enabled state when we click on run now button its throwing a error 
* Expected
Run now button should be disabled state until the all fields load
Removed the hardcoded false and altered the condition for local execution as  value for platform is undefined for local devices.

[TOS-1054] fix(dry-run-form) : fixed run button validation

---

ui/src/app/components/webcomponents/lab-environments-info.component.ts
ui/src/assets/i18n/en.json

* Jira: https://testsigma.atlassian.net/browse/TOS-968
* Github Issue: https://github.com/testsigmahq/testsigma/issues/229
[Bug]: Operation System details shows under the Browser details icon in Test Lab Type
* What is the current behavior?
The Operating system details shows in Browser details icon in the Test Plan under Test Lab Type
Operating system details icon is missing
* What is the expected behavior?
Operating System details should display in separate icon
added a span tag containing the respective os version and the respective os icon
* Note:
The webpage is loading very slow, not sure why

[TOS-968] fix(lab-environments-info) : added support for OS icon in test plan page

---

ui/src/app/components/results/list.component.html
ui/src/app/components/results/list.component.ts

JIra: https://testsigma.atlassian.net/browse/TOS-966
Removed the HTML tags by adding a remove tags function which returns the string without the tags and rendered it.

Fix[TOS-966] : Test Plan Descriptions collapsed in run results window.

---

ui/src/app/components/cases/list.component.html
ui/src/assets/i18n/en.json

* Jira: https://testsigma.atlassian.net/browse/TOS-254
Inappropriate message displayed when no Testcases/Step Groups are present in Trash 
* Actual
“No Step Groups created yet/No Test cases created yet” Message is displayed to user
* Expected
“No Test cases/Step groups added to Trash yet”
made the appropriate changes in list.component.html and en.json

[TOS-254] fix(list.component) : Changing the text for empty trash testCase/stepGroup list

---

ui/src/app/components/webcomponents/test-plan-platform-os-version-form.component.ts
ui/src/app/components/webcomponents/test-plan-test-machine-form.component.ts

**Jira Ticket**:  https://testsigma.atlassian.net/browse/TOS-969
Actual:
-  When we select the Local Devices in Web to run options in ad-hoc runner, the Browser Name is not shown sometimes/ disappears in few seconds.
- Issue exists in Mac OS and Windows OS. Works fine in Linux. 
Expected: 
- The default set browser name must be displayed correctly, and must not disappear when shifting between Testsigma Lab and Local Devices tab in Ad-hoc Run Page.
Fix:
- Removed the call to fetchPlatforms() function if Hybrid -- Local Executions.
-  Added a 'IF' check to fetchBrowsers() function for Hybrid executions.

[TOS-969] fix: Browser name does not display on Local Devices selections.

---

ui/src/app/components/webcomponents/action-step-result-details.component.ts

Jira: https://testsigma.atlassian.net/browse/TOS-774
**Actual**
-In dry runs, the details of the first viewed element are displayed for all other elements.
**Expected**
-For each element used in each test step, the specific element’s details should be displayed.
Fix: Removed the existing if condition, which allows the element details corresponding to the selected test step to be displayed. The code earlier had an **if (!this.ElementDetails)**, which gets populated for the first step alone and then never becomes empty, thus displaying the first element details for all steps irrespective of their element details.

[TOS-774]fix: Element details are not displayed properly in Dry Runs.

---

ui/src/app/components/webcomponents/create-test-group-from-step-form.component.ts

JIRA: https://testsigma.atlassian.net/browse/TOS-985
**Description**
When the user creates a step group by selecting test steps in a test case, after clicking on the create button, the page does not redirect to the created step group.
**Actual**
After creation of step group by selecting test steps in a test case, the page does not redirect to created step group page.
**Expected**
After creation of step group by selecting test steps in a test case, the page should redirect to created step group page.
Fix: 
Added a function that gets called to redirect to the new window, containing the step group details.

fix:[TOS-985] - Step Group Creation from Test Case does not redirect to created step group.

---

agent/src/main/java/com/testsigma/agent/mobile/ios/IosDeviceService.java
agent/src/main/java/com/testsigma/agent/mobile/ios/WdaService.java
automator/src/com/testsigma/automator/drivers/mobile/MobileDriver.java
automator/src/com/testsigma/automator/mobile/ios/AppInstaller.java
automator/src/com/testsigma/automator/mobile/ios/IosDeviceCommandExecutor.java
server/src/main/java/com/testsigma/controller/recorder/TestStepsRecorderController.java

Background: 
Currently, a user needs to install idb to run executions on IOS emulators. We want to move away from idb to xcrun so that users don’t require any installations.
https://testsigma.atlassian.net/browse/TOS-1093

[TOS-1093] (feat): Add support for IOS executions to run in local without idb installation

---

agent/src/main/java/com/testsigma/agent/services/AgentService.java

Jira: https://testsigma.atlassian.net/browse/TOS-659
Actual
OS version is displayed as windows v10 instead of v11 in Adhoc Run page of Local device and Agents List Page
Expected
OS version to be displayed as windows v11 in Adhoc Run page of Local device and Agents List Page
Fix
Added a condition to check the os_name and display the respective version number. instead of checking build number, we now check os name startsWith.

[TOS-659] fix(AgentService) : support for windows 11 with OS_NAME

---

ui/src/app/components/webcomponents/action-step-form.component.ts

**JIRA**: https://testsigma.atlassian.net/browse/TOS-1042 
**Actual**
Trying to clear one character in the test data value but its deletes the complete text.
**Expected**
It should not delete complete text 
Fix:
The backspace event triggers the **selectDataType** function causing it to assign the data value to empty, hence we are restricting this call. Removing the call could break the functionality in multiple places, hence restricting the condition alone.

Fix[TOS-1042]: Trying to clear one character in test data value but its deleting complete text

---

server/src/main/java/com/testsigma/dto/StepDetailsDTO.java
ui/src/app/components/webcomponents/action-step-result-details.component.ts
ui/src/app/models/step-details.model.ts

**Actual**
Test case results in page step prerequisite field displaying as NaN 
**Expected**
it should show the prerequisite test step number
Fix:  
De-serialized the order_id property in the front end by alias-ing with position in the step details model.
Removed the annotation from the backend in Step Details DTO, as that fix was not working. Retained the removal of +1 to display the correct step order of the pre-requisite, which otherwise displays the position+1 of the pre-requisite step.

[TOS-1044] fix: Prerequisite Step number displayed as NaN

---

agent/src/main/resources/agent.properties
automator/pom.xml
deploy/docker/docker-compose.yml
server/src/main/java/com/testsigma/dto/AgentDTO.java
server/src/main/resources/application.properties

The chromedriver team has stopped publishing the chromedriver releases and metadata using their traditional [chromedriver download repository](https://chromedriver.chromium.org/downloads) with chromedriver 114. This way, as of chromedriver 115, the chromedriver releases can only be discovered programmatically using the [Chrome for Testing (CfT) JSON endpoints](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints).
This change is very relevant for WebDriverManager, since, as of Chrome 115 and 116, chromedriver cannot be managed automatically by WebDriverManager using the traditional way. Therefore, for older versions of WebDriverManager, this situation led to errors like the following:
`io.github.bonigarcia.wdm.online.HttpClient: Error HTTP 404 executing …

[TE-11836]: Version upgrade for driver manager build

---

agent/src/main/resources/agent.properties
deploy/docker/docker-compose.yml
server/src/main/java/com/testsigma/dto/AgentDTO.java
server/src/main/resources/application.properties

The chromedriver team has stopped publishing the chromedriver releases and metadata using their traditional [chromedriver download repository](https://chromedriver.chromium.org/downloads) with chromedriver 114. This way, as of chromedriver 115, the chromedriver releases can only be discovered programmatically using the [Chrome for Testing (CfT) JSON endpoints](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints).
This change is very relevant for WebDriverManager, since, as of Chrome 115 and 116, chromedriver cannot be managed automatically by WebDriverManager using the traditional way. Therefore, for older versions of WebDriverManager, this situation led to errors like the following:
io.github.bonigarcia.wdm.online.HttpClient: Error HTTP 404 executing …

[TE-11836]: Webdrivermanager and version upgrade
