server/src/main/resources/db/migration/V5__test_devices_and_uploads_changes.sql
=> TOS-114 migrations corrected

server/src/main/java/com/testsigma/controller/TestCasesController.java, server/src/main/java/com/testsigma/model/TestCase.java, server/src/main/java/com/testsigma/repository/TestCaseRepository.java, server/src/main/java/com/testsigma/service/TestCaseService.java, server/src/main/resources/db/bootstrap/V18__test_cases.sql, server/src/main/resources/db/migration/V14__is_active_test_cases.sql
[TOS-281] Able to create a test case with same name.
[TOS-281]: https://testsigma.atlassian.net/browse/TOS-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TOS-281] Able to create a test case with same name.

ui/src/app/components/cases/list.component.html, ui/src/app/components/data/list.component.html, ui/src/app/components/elements/list.component.html, ui/src/app/components/environments/list.component.html, ui/src/app/components/plans/list.component.html, ui/src/app/components/plans/list.component.ts, ui/src/app/components/results/list.component.html, ui/src/app/components/results/list.component.ts, ui/src/app/components/suites/list.component.html, ui/src/app/components/suites/list.component.ts, ui/src/app/components/uploads/list.component.html, ui/src/app/shared/directives/sort.directive.ts, ui/src/app/shared/shared.module.ts, ui/src/scss/_list_card.scss
Added Quick Sort for sorting columns
=> TOS-284  Added Quick Sort for sorting columns

ui/src/app/components/webcomponents/test-plan-app-uploads-form.component.ts, ui/src/app/components/webcomponents/test-plan-device-form.component.html, ui/src/app/components/webcomponents/test-plan-execution-environment-info.component.ts, ui/src/app/components/webcomponents/test-plan-suite-selection.component.html, ui/src/app/shared/components/webcomponents/desired-capabilities.component.html
Create Test Plan : Styling Issues Correction
=> TOS-319 Create Test Plan : Styling Issues Correction

server/src/main/resources/db/bootstrap/V23__upload_versions.sql, server/src/main/resources/db/migration/V25__upload_versions_changes.sql, ui/src/app/shared/components/webcomponents/uploads-form.component.html, ui/src/app/shared/components/webcomponents/uploads-form.component.ts, ui/src/app/shared/services/upload.service.ts
TOS-340 Upload Versioning : Edit upload option
=> TOS-340 Upload Versioning : Edit upload option

server/src/main/java/com/testsigma/dto/UserPreferenceDTO.java, server/src/main/java/com/testsigma/model/UserPreference.java, server/src/main/java/com/testsigma/web/request/UserPreferenceRequest.java, server/src/main/resources/db/bootstrap/V2__user_preferences.sql, server/src/main/resources/db/migration/V27__add_showed_github_star.sql, ui/src/app/components/webcomponents/left-nav.component.ts, ui/src/app/models/user-preference.model.ts
TOS-390 Github Stars : Show a popup after 15 minutes in account for user
=> TOS-390 Github Stars : Show a popup after 15 minutes in account for user

server/src/main/java/com/testsigma/web/request/UserPreferenceRequest.java, ui/src/app/components/webcomponents/left-nav.component.ts, ui/src/app/shared/components/webcomponents/testsigma-github-star-love.component.html, ui/src/app/shared/components/webcomponents/testsigma-github-star-love.component.ts, ui/src/app/shared/shared.module.ts
TOS-433 GitHub Stars : Remove Twitter CTA
=> TOS-433 GitHub Stars : Remove Twitter CTA

server/src/main/java/com/testsigma/config/StorageServiceFactory.java, server/src/main/java/com/testsigma/controller/StorageConfigController.java, server/src/main/java/com/testsigma/exception/GlobalExceptionHandler.java, server/src/main/java/com/testsigma/exception/InvalidStorageCredentialsException.java, server/src/main/java/com/testsigma/service/AwsS3StorageService.java, server/src/main/java/com/testsigma/service/AzureBlobStorageService.java, server/src/main/java/com/testsigma/service/StorageConfigService.java, ui/src/app/services/storage-config.service.ts, ui/src/app/settings/components/storage/aws/create.component.ts, ui/src/app/settings/components/storage/aws/details.component.ts, ui/src/app/settings/components/storage/azure/create.component.ts, ui/src/app/settings/components/storage/azure/details.component.ts, ui/src/app/settings/components/storage/storage.component.ts, ui/src/app/shared/components/base.component.ts, ui/src/app/shared/components/webcomponents/uploads-form.component.ts
TOS-126 Validating storage credentials before saving
=> TOS-126 Validating storage credentials before saving

ui/src/app/agents/components/webcomponents/selected-elements-container.component.ts
TOS-363 Appended timestamp for names and screen name with length less than 4
=> TOS-363 Appended timestamp for names with length less than 4 

agent/src/main/resources/agent.properties, server/src/main/java/com/testsigma/controller/ElementsController.java, server/src/main/java/com/testsigma/service/AgentExecutionService.java, server/src/main/java/com/testsigma/specification/TestStepSpecification.java, server/src/main/resources/application.properties, ui/src/app/agents/components/webcomponents/mobile-step-recorder.component.html, ui/src/app/agents/components/webcomponents/mobile-step-recorder.component.ts, ui/src/app/app.module.ts, ui/src/app/components/webcomponents/action-step-form.component.ts, ui/src/app/components/webcomponents/action-test-data-runtime-variable-suggestion.component.html, ui/src/app/components/webcomponents/action-test-data-runtime-variable-suggestion.component.ts, ui/src/app/components/webcomponents/test-case-action-steps.component.html, ui/src/app/components/webcomponents/test-case-steps-list.component.ts, ui/src/app/models/test-step.model.ts, ui/src/app/services/mobile-recorder-event.service.ts, ui/src/assets/i18n/en.json
=> 1.7.0 Release

ui/src/app/agents/components/agent-form.component.html, ui/src/app/agents/components/list.component.html, ui/src/app/agents/components/webcomponents/agents-auto-complete.component.ts, ui/src/app/components/cases/steps-list.component.html, ui/src/app/components/onboarding-form.component.html, ui/src/app/components/plans/plugs.component.html, ui/src/app/components/support.component.html, ui/src/app/components/webcomponents/action-step-form.component.html, ui/src/app/components/webcomponents/action-test-data-environment-suggestion.component.html, ui/src/app/components/webcomponents/action-test-data-parameter-suggestion.component.html, ui/src/app/components/webcomponents/element-form.component.html, ui/src/app/components/webcomponents/get-started-base.component.ts, ui/src/app/components/webcomponents/quick-start.component.ts, ui/src/app/components/webcomponents/select-test-lab.component.ts, ui/src/app/components/webcomponents/telemetry-notification.component.ts, ui/src/app/components/webcomponents/test-step-group-form.component.html, ui/src/app/components/webcomponents/why-test-case-failed-help.component.ts, ui/src/app/shared/components/webcomponents/inspection-modal.component.html
=> TOS-572 - nofollow to testsigma domain links

server/src/main/java/com/testsigma/constants/MessageConstants.java, server/src/main/java/com/testsigma/controller/JunitReportsController.java, server/src/main/java/com/testsigma/controller/TestCaseResultsController.java, server/src/main/java/com/testsigma/controller/TestDeviceResultsController.java, server/src/main/java/com/testsigma/controller/TestPlanResultsController.java, server/src/main/java/com/testsigma/controller/TestSuiteResultsController.java, server/src/main/java/com/testsigma/model/ReRunType.java, server/src/main/java/com/testsigma/model/TestCaseResult.java, server/src/main/java/com/testsigma/model/TestPlanResult.java, server/src/main/java/com/testsigma/model/TestStepConditionType.java, server/src/main/java/com/testsigma/model/TestStepType.java, server/src/main/java/com/testsigma/repository/StepResultScreenshotComparisonRepository.java, server/src/main/java/com/testsigma/service/StepResultScreenshotComparisonService.java, server/src/main/java/com/testsigma/service/TestCaseResultService.java, server/src/main/java/com/testsigma/service/TestDeviceResultService.java, server/src/main/java/com/testsigma/service/TestPlanResultService.java, server/src/main/java/com/testsigma/service/TestSuiteResultService.java, server/src/main/java/com/testsigma/util/XLSUtil.java, ui/src/app/components/results/suite-result-details.component.html, ui/src/app/components/results/test-case-result-details.component.html, ui/src/app/components/results/test-machine-result-details.component.html, ui/src/app/components/webcomponents/test-case-results.component.html, ui/src/app/components/webcomponents/test-machine-results.component.html, ui/src/app/components/webcomponents/test-suite-results.component.html, ui/src/assets/i18n/en.json
>Added XLS export option
>Added Junit export option
>   https://testsigma.atlassian.net/browse/TOS-485
=> [TOS 485] Added export field in all places 

automator/src/com/testsigma/automator/webservices/RestApiResponseValidator.java, ui/src/app/components/cases/test-case-form.component.html, ui/src/app/components/cases/test-case-form.component.ts, ui/src/app/components/data/create.component.html, ui/src/app/components/data/create.component.ts, ui/src/app/components/data/edit.component.html, ui/src/app/components/data/edit.component.ts, ui/src/app/components/environments/form.component.html, ui/src/app/components/environments/form.component.ts, ui/src/app/components/plans/form.component.ts, ui/src/app/components/plans/test-plan-editor/test-plan-machine-selection-form.component.html, ui/src/app/components/plans/test-plan-editor/test-plan-machine-selection-form.component.ts, ui/src/app/components/suites/form.component.html, ui/src/app/components/suites/form.component.ts, ui/src/app/components/webcomponents/create-test-group-from-step-form.component.html, ui/src/app/components/webcomponents/create-test-group-from-step-form.component.ts, ui/src/app/components/webcomponents/schedule-plan-form.component.html, ui/src/app/components/webcomponents/test-case-clone-form.component.html, ui/src/app/components/webcomponents/test-case-clone-form.component.ts, ui/src/app/components/webcomponents/test-plan-form.component.html, ui/src/app/shared/components/webcomponents/uploads-form.component.html, ui/src/app/shared/components/webcomponents/uploads-form.component.ts, ui/src/app/workspaces/workspaces.component.ts
TOS-476 UX : Update Error messaging and Increase limits
Jira link : https://testsigma.atlassian.net/browse/TOS-476
In the name field, increased character limit from 126 to 250 and changed error message shown from 126 to 256
=> [TOS-476]  Update Error messaging and Increase limits

server/src/main/java/com/testsigma/dto/AgentDTO.java
=> updated agent version

ui/src/app/components/webcomponents/lab-environments-info.component.ts
>The "Test Lab" type (such as cloud or local ) icon to be displayed in the "Test Plan List Page" and in "Run Results List Page" 
>https://testsigma.atlassian.net/browse/TOS-678
=> [TOS 678] The "Test Lab" icon not displaying

ui/src/app/settings/components/provisioning_profiles/form.component.html, ui/src/app/settings/components/provisioning_profiles/form.component.ts, ui/src/app/workspaces/components/test-case-priorities.component.html, ui/src/app/workspaces/components/test-case-priorities.component.ts, ui/src/app/workspaces/components/test-case-types.component.html, ui/src/app/workspaces/components/test-case-types.component.ts, ui/src/app/workspaces/components/versions/form.component.html, ui/src/app/workspaces/components/versions/form.component.ts, ui/src/scss/_styles.scss
> "Failed To Create Version" error message is displayed instead of warning message stating "Name should be less than 250 chars" in Various places refere to descripton
> https://testsigma.atlassian.net/browse/TOS-680
=> [TOS 680] "Failed To Create Version" error message in workspace 

ui/src/app/components/cases/steps-list.component.html, ui/src/scss/_sizing.scss
>added search and reorder button Teststep(current) in dryrun page
=> adding reorder button in Teststeps(current) in dryrun page

ui/src/app/shared/components/webcomponents/auto-complete.component.ts
=> TOS-668 - dropdown full area selection

ui/src/app/components/webcomponents/tags-chip-list.component.ts, ui/src/app/components/webcomponents/test-plan-form.component.html
jira link : https://testsigma.atlassian.net/browse/TOS-707
=> [TOS 707] removing autofocus in label field

ui/src/app/components/plans/list.component.html, ui/src/app/components/suites/list.component.html
> The alignment has been corrected
>https://testsigma.atlassian.net/browse/TOS-692
=> [TOS 692] The alignment of Filter icon

ui/src/app/components/webcomponents/left-nav.component.ts, ui/src/app/shared/components/webcomponents/testsigma-github-star-love.component.html
Actual
The display of the Github popup is inappropriate → the popup is going beyond the screen
Expected
The display of the Github popup to be appropriate
Alignment of the Github Popup was fixed
=> TOS-761 The display of the Github popup is inappropriate

server/src/main/resources/db/migration/V42__migration_updates.sql
https://github.com/testsigmahq/testsigma/issues/172
=> [Bug]: Unable to view test cases and execute test cases after upgrading

server/src/main/java/com/testsigma/controller/TestDataSetsController.java, server/src/main/java/com/testsigma/dto/TestDataProfileDTO.java, server/src/main/java/com/testsigma/mapper/TestDataProfileMapper.java, server/src/main/java/com/testsigma/model/TestData.java, server/src/main/java/com/testsigma/model/TestDataSet.java, server/src/main/java/com/testsigma/repository/TestDataSetRespository.java, server/src/main/java/com/testsigma/schedulers/TestDataMigrationScheduler.java, server/src/main/java/com/testsigma/service/TestDataImportService.java, server/src/main/java/com/testsigma/service/TestDataProfileService.java, server/src/main/java/com/testsigma/service/TestDataSetService.java, server/src/main/java/com/testsigma/service/TestStepResultService.java, server/src/main/java/com/testsigma/specification/TestDataSetSpecification.java, server/src/main/java/com/testsigma/specification/TestDataSetSpecificationBuilder.java, server/src/main/resources/db/bootstrap/V17__test_data.sql, server/src/main/resources/db/bootstrap/V60__test_data_sets.sql, server/src/main/resources/db/migration/V43__add_test_data_sets.sql, server/src/main/resources/db/migration/V44__add_is_migrated_column_in_test_data.sql, ui/src/app/components/webcomponents/action-test-data-parameter-suggestion.component.ts
https://testsigma.atlassian.net/browse/TOS-809
=> TOS-809 Migrate data from test_data table to a separate table

ui/src/app/components/webcomponents/test-plan-device-form.component.html, ui/src/app/shared/components/webcomponents/auto-complete.component.ts, ui/src/assets/i18n/en.json
when a device not available during the selection of testdevice from either Adhoc run page or testdevice linking in testplan, we are showing block icon without giving any context to the user. In this enhancement i added a tooltip.
=> feat:TOS-437 Device Not Available : Add on Hover Text

ui/src/app/components/elements/list.component.html, ui/src/app/components/elements/list.component.ts
Added search option in elements list page
=> feat:TOS-843 Need search option On elements list page

server/src/main/java/com/testsigma/constants/NaturalTextActionConstants.java, server/src/main/java/com/testsigma/controller/recorder/NLPTemplatesController.java, server/src/main/java/com/testsigma/dto/TestStepDTO.java, server/src/main/java/com/testsigma/mapper/recorder/NLPTemplateMapper.java, server/src/main/java/com/testsigma/model/recorder/TestStepRecorderDTO.java, server/src/main/java/com/testsigma/model/recorder/TestStepRecorderDataMap.java, server/src/main/java/com/testsigma/model/recorder/TestStepRecorderForLoop.java
=> [TOS-897] [Refactor] - Step + NLP API should support camelCase version of key instead of kebab-case

server/src/main/java/com/testsigma/service/RunTimeDataService.java
=> [ TOS - 911 ] fix(recorder): Runtime variables not displaying in OS using recorder

.github/workflows/create_jira_ticket.yml, action.js
Added GitHub action to create a ticket in Jira when an issue is raised in Github
=> TRD-175 - Added GitHub action to create ticket in Jira

.github/workflows/create_jira_ticket.yml
> Changing the js file name in yml file
=> TRD-175-Correcting the file name

ui/src/app/components/webcomponents/test-step-more-action-form.component.html, ui/src/app/components/webcomponents/test-step-more-action-form.component.ts
for FOR_LOOP in that prerequistie dropdown it is showing as null.
=> fix(TestStep) : Fixes teststeps displaying as null in prerequisite select

server/src/main/java/com/testsigma/repository/TestStepRepository.java, server/src/main/java/com/testsigma/service/ElementService.java, server/src/main/java/com/testsigma/service/TestStepService.java
Jira: https://testsigma.atlassian.net/browse/TOS-999
Actual
Element name updating in the imported version also
Expected
It should not update the imported version
It should update within the version only
Fix
in the query to update element name in teststep repository, i have added a third parameter where it checks for the workspace version id when it is triggered to update.
this way only test step using this element will be updated in the same version and not in the other versions.
=> [TOS-999] fix(TestStepRepository) : element name change, changes in all versions

server/src/main/java/com/testsigma/controller/UploadsController.java, server/src/main/java/com/testsigma/service/UploadService.java, ui/src/app/components/uploads/list.component.html, ui/src/app/components/uploads/list.component.ts, ui/src/app/shared/components/webcomponents/upload-entities-modal.component.ts, ui/src/app/shared/components/webcomponents/uploads-entities-modal.component.html, ui/src/assets/i18n/en.json
Jira Tickets
https://testsigma.atlassian.net/browse/TOS-989
https://testsigma.atlassian.net/browse/TOS-992
Description
Fixed the bulk upload deletion while used in Test Plans and Test Cases.[Child Tickets of TOS 782]
Fix does not allow the deletion of an upload used in a Test Plan as a Test Machine.
Added a linked test plans pop-up along with the TEST PLAN NAME with its corresponding TEST MACHINE.
=> [TOS-992//TOS-989] Do not Allow deletion of uploads when used in Test Plans and add Test Plan Name to popup.

server/src/main/java/com/testsigma/service/UploadService.java, server/src/main/java/com/testsigma/specification/TestCaseSpecification.java, ui/src/app/components/uploads/list.component.ts
Fixed uploads deletion for multi-test data using data maps instead of Test Data.
=> [TOS-992] - Fixed Uploads Deletion for multi test data support

server/src/main/java/com/testsigma/dto/export/ElementXMLDTO.java, server/src/main/java/com/testsigma/dto/export/ForLoopConditionXMLDTO.java, server/src/main/java/com/testsigma/mapper/TestStepMapper.java, server/src/main/java/com/testsigma/service/BackupDetailService.java, server/src/main/java/com/testsigma/service/ForLoopConditionService.java, server/src/main/java/com/testsigma/service/XMLExportImportService.java
=> feat(TE-7525): Import from OS to Cloud

ui/src/app/components/webcomponents/get-started-base.component.ts
* Jira: https://testsigma.atlassian.net/browse/TOS-1051
Throwing errors in Network tab
* Actual
throwing unnecessary network logs
* Expected
It should not throw unnecessary network logs
Removed the format("YYYY-MM-DD") for both fetchDryTestCaseCount and fetchTestDataCount functions.
=> [TOS-1051] fix(get-started-base): removed the date format for query

ui/src/app/components/webcomponents/action-step-form.component.ts
* Jira : https://testsigma.atlassian.net/browse/TOS-983
Even if TDP is mapped, while running the test its shows TDP is not available
The test data profile is mapped to the test case yet while running the test it shows NO TDP is associated.
This happens with a particular test case but if the same TDP is mapped to other test it works
added a if condition so that testDataProfileStepId is serialised only if the testStep is of type 'FOR_LOOP'
=> [TOS-983] fix(action-step-form) : adding if condition for setting testDataProfileStepId

deploy/docker/build.sh, server/src/main/java/com/testsigma/controller/recorder/TestStepsRecorderController.java, server/src/main/java/com/testsigma/mapper/recorder/TestStepRecorderMapper.java, server/src/main/java/com/testsigma/model/recorder/TestStepRecorderDTO.java, server/src/main/java/com/testsigma/service/TestStepService.java
Jira Issue: https://testsigma.atlassian.net/browse/TOS-1017
Changes: Allowed nested steps and returned only main parent steps.
=> (feat): Add nested steps in the test steps API for the response

ui/src/app/models/test-step.model.ts
* Jira : https://testsigma.atlassian.net/browse/TOS-1069
*Steps for reproduce
Create a test case 
Create a click nlps test steps
Check the element color
and create an enter template and check the element color
* Actual
Element color not displaying for click NLPs
* Expected
It should show the element color
* Fix
Changed the if condition so that non-if nlp step can also be passed in parsedStep
=> [TOS-1069] fix(test-step.model) : fixed the if condition for parsedStep

server/src/main/java/com/testsigma/repository/WorkspaceVersionRepository.java
* Jira : https://testsigma.atlassian.net/browse/TOS-1046
Getting Problem while start Execution error when we executed copied test plans
Create a test case, suites and Test plan
Run the test plan
Now click on workspace settings
Choose version and copied version
Now switch to copied version
Now navigate to test plan page 
Run the test plan and check the executions
* Actual
Its showing Problem while start Execution
* Expected
It should not show error
It should execute test plans without any errors
changed the query to copy **workspace_version_id**, and **test_lab_type** while cloning version
=> [TOS-1046] fix: fixed query when copying test_devices while cloning version

ui/src/app/components/cases/test-case-details.component.html, ui/src/app/components/webcomponents/action-step-result-details.component.ts
* Jira : https://testsigma.atlassian.net/browse/TOS-949
* Cloud Ticket : https://testsigma.atlassian.net/browse/TE-6879
App Details : Show App and VersionID
* Add App Details in the following way 
App Details
* App
Name 
ID
* Version
Name 
ID
=> [TOS-949] feat: App Details : Show App and VersionID

ui/src/app/components/webcomponents/import-form.component.html, ui/src/app/shared/components/webcomponents/auto-complete.component.ts, ui/src/app/workspaces/components/versions/form.component.html, ui/src/app/workspaces/components/versions/form.component.ts
* Jira : https://testsigma.atlassian.net/browse/TOS-766
Navigate to Workspace settings page
Click on Version
Click on “+ New Version“
Enter name less than 4 chars
Click on Create button and observe
* Actual
Able to create version with name less than 4 chars 
* Expected
Should not be able to create version with name less than 4 chars and also an error messgae to be displayed when clicked n create button stating “Version name should have atleast minimum of 4 characters“
added validation check for version name for min character of 4.
=> [TOS-766] fix(forms.component): added version name validation for min 4 characters

ui/src/app/components/cases/test-case-details.component.html
* Jira ; https://testsigma.atlassian.net/browse/TOS-1030
Navigate to mobile web application
Now create a test case
Now check the Record button for mobile web
* Actual
The record button not displaying for mobile web applications
* Expected
The record button should show for mobile web also
added check for isMobileWeb in ngIf
=> [TOS-1030] fix (test-case-details): added record button for mobile web

ui/src/app/components/cases/test-case-details.component.html, ui/src/app/components/environments/details-header.component.html, ui/src/app/workspaces/components/test-case-priorities.component.html, ui/src/app/workspaces/components/test-case-types.component.html
* Jira : https://testsigma.atlassian.net/browse/TOS-242
Lower Case Characters like g,j,y are cut in display of -->(Test case name,Types,priorities,environments stepgroup name etc...)
Click on Workspace settings
Click on Testcase types
* Actual
The above mentioned characters are cut
* Expected
The above mentioned characters should not be cut
removed text-truncate in test-case-types.component.html
=> [TOS-242] fix: cut character at bottom is fixed

ui/src/app/components/webcomponents/element-form.component.html
**JIRA**: https://testsigma.atlassian.net/browse/TOS-979
Need to change the screen name validation.
**Actual**
Currently, its displaying Title is mandatory
**Expected**
It should show Screen Name is Mandatory
=> [TOS-979]fix: Changed the locator name.

ui/src/app/components/webcomponents/backup-form.component.html, ui/src/app/shared/components/webcomponents/auto-complete.component.ts
Jira : https://testsigma.atlassian.net/browse/TOS-977
Already created a PR for import form,
added commit for export form
=> [TOS-977] fix: alignment fix in export form

ui/src/app/components/webcomponents/test-case-result-filter.component.html, ui/src/app/components/webcomponents/test-case-result-filter.component.ts, ui/src/assets/i18n/en.json
* Jira : https://testsigma.atlassian.net/browse/TOS-694
Create Test Plan
Execute the Test plan
goto the View reports page
Click on Filter icon and observe
* Actual
The Fields such as "Labels , Created date and Updated date" are not displayed under the Filter overlay in the Run Results Page
* Expected
The Fields such as "Labels , Created date and Updated date" to be displayed under the Filter overlay in the Run Results Page
added label, created date and updated date in the filter and changed the corresponding condition to disable the filter button
=> [TOS-694] fix(test-case-result-filter): label, dates added to filter

automator/pom.xml
=> [TE-11836]: Upgraded WebDriverAgent Version to 5.4.1 
